language: node_js
node_js:
  - 'v4'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'js-mock' ]; then cd .. && eval "mv $currentfolder js-mock" && cd js-mock; fi
  - npm install -g grunt-cli
install:
  - npm install
after_success:
  - grunt coveralls
